apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
  labels:
    app: {{template "common.name" .}}
data:
  run.sh: |
    #!/usr/bin/env bash
    set -eu -o pipefail

    # Currently we are unable to write to /functions directory and requires
    # a change to the Dockerfile
    # Hence copy venv and the connector app contents for work-dir(git-sync)
    # to a place where we have access and run from there
    mkdir -p /tmp/app && cd /tmp/app
    cp -r "${HASURA_CONFIGURATION_DIRECTORY}/." /tmp/app/

    {{- if not .Values.initContainers.gitSync.depsPackaged }}
    cp -r /functions/venv /tmp/app/
    {{- end }}

    # source python virtual env and exec python3 to ensure that
    # it is the root process in the container, so that signals (ie SIGTERM)
    # are propagated properly.
    . venv/bin/activate && exec python3 functions.py serve --configuration ./
