apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  {{- if .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET }}
  HASURA_SERVICE_TOKEN_SECRET: {{ required "Error: .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET is required!" .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  {{- end }}
  {{- range $key, $val := .Values.connectorCustomEnvVars }}
  {{- if $val }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
