apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  {{- if .Values.serviceEnvVars.PASSWORD }}
  PASSWORD: {{ required "Error: .Values.serviceEnvVars.PASSWORD is required!" .Values.serviceEnvVars.PASSWORD | b64enc | quote }}
  {{- end }}
