useReleaseName: false

additionalAnnotations: |
  checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}

# Container Configs
image:
  repository: ""
  tag: ""
  pullPolicy: Always
replicas: "1"
wsInactiveExpiryMins: "1"
securityContext:
  runAsNonRoot: true
  runAsGroup: 1000
  runAsUser: 100
  fsGroup: 1000

healthChecks:
  enabled: false
  livenessProbePath: "/healthz"
  readinessProbePath: "/healthz"

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target 50% CPU utilization per pod
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Target 80% memory utilization per pod

resources: |
  requests:
    cpu: "250m"
    memory: "250Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

serviceEnvVars:
  ADFS_PROVIDER_ENDPOINT: ""
  REGION: ""
  RESOURCE: ""

env: |
  - name: ADFS_PROVIDER_ENDPOINT
    value: {{ .Values.serviceEnvVars.ADFS_PROVIDER_ENDPOINT | quote }}
  - name: REGION
    value: {{ .Values.serviceEnvVars.REGION | quote }}
  - name: RESOURCE
    value: {{ .Values.serviceEnvVars.RESOURCE }}

