useReleaseName: true

additionalAnnotations: |
  checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}

# Container Configs
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
replicas: "1"
wsInactiveExpiryMins: "1"
securityContext:
  runAsNonRoot: true
  runAsGroup: 1000
  runAsUser: 1000
  fsGroup: 1000

initContainers:
  gitSync:
    enabled: false
    repo: "git@github.com:<org>/<repo>"
    branch: "main"

healthChecks:
  enabled: false
  livenessProbePath: "/healthz"
  readinessProbePath: "/healthz"

command: |
  - bash
  - /scripts/run.sh

extraVolumes: |
  - name: run-script
    configMap:
      name: {{ printf "%s-config" (include "common.name" .) }}

extraVolumeMounts: |
  - name:  run-script
    mountPath: /scripts/run.sh
    subPath: run.sh

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target 50% CPU utilization per pod
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Target 80% memory utilization per pod

resources: |
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

connectorEnvVars:
  HASURA_SERVICE_TOKEN_SECRET: ""
  configDirectory: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://dp-otel-collector:4317"
  OTEL_SERVICE_NAME: ""

env: |
  {{- if .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET }}
  - name: HASURA_SERVICE_TOKEN_SECRET
    valueFrom:
      secretKeyRef:
        key: HASURA_SERVICE_TOKEN_SECRET
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: {{ .Values.connectorEnvVars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  {{- if .Values.connectorEnvVars.OTEL_SERVICE_NAME }}
  - name: OTEL_SERVICE_NAME
    value: {{ .Values.connectorEnvVars.OTEL_SERVICE_NAME }}
  {{- else }}
  - name: OTEL_SERVICE_NAME
    value: {{ .Chart.Name }}
  {{- end }}
  {{- if .Values.connectorEnvVars.configDirectory }}
  - name: HASURA_CONFIGURATION_DIRECTORY
    value: {{ .Values.connectorEnvVars.configDirectory }}
  {{- end }}
