{{- define "common.serviceaccount" -}}
{{- $serviceName := include "common.name" . -}}
{{- if or (((.Values.global).serviceAccount).enabled) ((.Values.serviceAccount).enabled) -}}
---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}
metadata:
  name: {{ (.Values.serviceAccount).name | default $serviceName }}
  namespace: {{ template "common.namespace" . }}
{{- with (.Values.serviceAccount).additionalAnnotations }}
  annotations:
  {{- include "common.tplOrYaml" (set (deepCopy $) "value" .) | nindent 4 }}
{{- end }}
  labels:
{{- include "common.labels" . | nindent 4 }}
{{- include "common.derivedLabels" . | indent 4 }}
{{- end }}
{{- end -}}
