{{- define "common.externalsSecretsConfig" -}}
{{- $serviceName := include "common.name" . -}}
{{- if eq "true" (include "common.enableExternalSecretsSupport" .) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-ext-secrets-config" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  secret-refresh-config.yaml: |-
{{ tpl .Values.externalSecrets.secretRefresher.configYaml . | indent 4 }}
  secret-refresh-init-config.yaml: |-
{{ tpl .Values.externalSecrets.secretRefresher.configYaml (merge (dict "externalSecretsOverrideType" "initcontainer") .) | indent 4 }}
{{- end }}
{{- end -}}  