lakekeeper:
  enabled: true
  pgEncryptionKey: ""
  fullnameOverride: "lakekeeper"
  preInstallMigration:
    annotations:
      helm.sh/hook: pre-install
      helm.sh/hook-delete-policy: before-hook-creation
  bootstrap:
    cloud: "aws"
    apiUrl: "http://lakekeeper.promptql.svc.cluster.local:8181"
    warehouseName: "iceberg"
    s3Bucket: ""
    s3Region: ""
    annotations:
      helm.sh/hook: post-install
      helm.sh/hook-delete-policy: before-hook-creation
  catalog:
    # -- Number of replicas to deploy. Replicas are stateless.
    replicas: 2

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    config:
      LAKEKEEPER__ENABLE_AWS_SYSTEM_CREDENTIALS: "true"
      LAKEKEEPER__ENABLE_GCP_SYSTEM_CREDENTIALS: "true"
      LAKEKEEPER__ENABLE_AZURE_SYSTEM_CREDENTIALS: "true"


  secretBackend:
    # -- the type of secret store to use.
    # Available values: "Postgres", "KV2"
    type: "Postgres"

    # postgres specific configurations.
    postgres:
      # -- Name of the secret containing the encryption key. (Mandatory)
      encryptionKeySecret: "lakekeeper-pg-encryption"
      # -- Name of the key within `encryptionKeySecret` containing the encryption key string
      encryptionKeySecretKey: "encryptionKey"

  postgresql:
    enabled: false

  externalDatabase:
    # -- the type of external database.
    # allowed values: "postgres"
    type: postgres

    # -- hostname to use for read instances of the external database
    host_read: ""

    # -- hostname to use for write instances of the external database.
    # For single read/write instances, this should be the same as `host_read`
    host_write: ""

    # port of the external database
    port: 5432

    # the database/scheme to use within the external database
    database: lakekeeper

    # the username for the external database
    user: ""

    # the password for the external database
    # - [WARNING] to avoid storing the password in plain-text within your values,
    #   create a Kubernetes secret and use `externalDatabase.passwordSecret`
    password: ""

  authz:
    backend: "allowall"

  serviceAccount:
    # -- Specifies whether a service account should be created.
    # If `false`, you must create the you must create the service account outside this chart with name: `serviceAccount.name`
    create: true

trino:
  enabled: false
  cloud: "aws"
  fullnameOverride: "trino"
  catalogs: ""

  coordinator:
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    additionalVolumes:
      - name: trino-catalog
        configMap:
          name: trino-catalog
    additionalVolumeMounts:
      - name: trino-catalog
        mountPath: /etc/trino/catalog

  worker:
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    additionalVolumes:
      - name: trino-catalog
        configMap:
          name: trino-catalog
    additionalVolumeMounts:
      - name: trino-catalog
        mountPath: /etc/trino/catalog

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "trino"
