apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  HASURA_SERVICE_TOKEN_SECRET: {{ .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  MONGODB_DATABASE_URI: {{ .Values.connectorEnvVars.MONGODB_DATABASE_URI | b64enc | quote }}
{{- if .Values.otel.deployOtelCollector }}
  otel-collector-config.yaml: {{ (tpl .Values.otel.config .) | b64enc | quote }}
{{- end }}