{{ $name := "lakekeeper-pg-encryption" }}
{{ $namespace := .Release.Namespace }}
{{ $labels := include "common.labels" . }}
---
{{ if and .Values.lakekeeper.enabled .Values.lakekeeper.pgEncryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
data:
  encryptionKey: {{ .Values.lakekeeper.pgEncryptionKey | b64enc | quote }}
{{- end }}
