{{- $namespace := include "common.namespace" $ -}}
{{- $serviceName := include "common.name" . -}}
{{- with .Values.configs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
data: 
  rate-limit.json: |
    {
      "redis_url": "redis://{{ $serviceName }}-redis:6379",
      {{- .enginePluginRateLimitConfig.otherConfig | nindent 6 }}
    }
{{- end }}