{{- $namespace := include "common.namespace" $ -}}
{{- $serviceName := include "common.name" . -}}
{{- with .Values.configs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
data: 
  configuration.json: |
    {
      "headers": {
        "hasura-m-auth": "{{ .enginePluginRateLimitAuthToken }}"
     }
    }
  rate-limit.json: |
{{ .enginePluginRateLimitConfig | indent 4 }}
{{- end }}