apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  configuration.json: {{ printf "{\"headers\": {\"hasura-m-auth\": %s}}" (.Values.secrets.enginePluginRateLimitAuthToken | quote) | b64enc | quote }}
