apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  configuration.json: |
    {
      "headers": {
        "hasura-m-auth": {{ .Values.secrets.enginePluginRateLimitAuthToken | quote }}
      }
    }