apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  HASURA_DDN_PLUGIN_AUTH_TOKEN: {{ required "Error: .Values.secrets.enginePluginRateLimitAuthToken is required!" .Values.secrets.enginePluginRateLimitAuthToken | b64enc | quote }}
