useReleaseName: true

additionalAnnotations: |
  checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
  app.kubernetes.io/access-group: connector

networkPolicy:
  ingress:
    enabled: true
    allowedApps:
      - v3-engine

# Container Configs
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
replicas: "1"
wsInactiveExpiryMins: "1"
securityContext:
  runAsNonRoot: true
  runAsGroup: 1000
  runAsUser: 1000
  fsGroup: 1000

serviceAccount:
  enabled: false
  name: ""

initContainers:
  gitSync:
    enabled: false
    repo: "git@github.com:<org>/<repo>"
    branch: "main"
    secretName: ""

healthChecks:
  enabled: false
  livenessProbePath: "/healthz"
  readinessProbePath: "/healthz"

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target 50% CPU utilization per pod
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Target 80% memory utilization per pod

resources: |
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

authProxy:
  enabled: false
  name: auth-proxy
  httpPort: 8081
  image:
    repository: ""
    tag: ""
    pullPolicy: Always
  authProxyEnvVars:
    ADFS_PROVIDER_ENDPOINT: ""
    REGION: ""
    RESOURCE: ""

extraContainers: |
  {{- if .Values.authProxy.enabled }}
  - name: {{ .Values.authProxy.name }}
    image: "{{ template "common.image" (dict "Values" $.Values "repository" .Values.authProxy.image.repository "tag" .Values.authProxy.image.tag) }}"
    ports:
      - name: {{ .Values.authProxy.name }}
        containerPort: {{ .Values.authProxy.httpPort }}
        protocol: TCP
    lifecycle:
      preStop:
        exec:
          command:
          - sh
          - -c
          - sleep 10
    resources:
      requests:
        cpu: "250m"
        memory: "250Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    env:
    - name: ADFS_PROVIDER_ENDPOINT
      value: {{ .Values.authProxy.authProxyEnvVars.ADFS_PROVIDER_ENDPOINT | quote }}
    - name: REGION
      value: {{ .Values.authProxy.authProxyEnvVars.REGION | quote }}
    - name: RESOURCE
      value: {{ .Values.authProxy.authProxyEnvVars.RESOURCE | quote }}
  {{- end }}

connectorEnvVars:
  HASURA_SERVICE_TOKEN_SECRET: ""
  ELASTICSEARCH_URL: ""
  ELASTICSEARCH_USERNAME: ""
  ELASTICSEARCH_PASSWORD: ""
  ELASTICSEARCH_API_KEY: ""
  ELASTICSEARCH_CA_CERT_PATH: ""
  ELASTICSEARCH_INDEX_PATTERN: ""
  ELASTICSEARCH_DEFAULT_RESULT_SIZE: ""
  HASURA_CREDENTIALS_PROVIDER_URI: ""
  ELASTICSEARCH_CREDENTIALS_PROVIDER_KEY: ""
  ELASTICSEARCH_CREDENTIALS_PROVIDER_MECHANISM: ""
  configDirectory: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://dp-otel-collector:4317"
  OTEL_SERVICE_NAME: ""

env: |
  {{- if .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET }}
  - name: HASURA_SERVICE_TOKEN_SECRET
    valueFrom:
      secretKeyRef:
        key: HASURA_SERVICE_TOKEN_SECRET
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  - name: ELASTICSEARCH_URL
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_URL
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_USERNAME }}
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_USERNAME
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_PASSWORD }}
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_PASSWORD
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_API_KEY }}
  - name: ELASTICSEARCH_API_KEY
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_API_KEY
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_CA_CERT_PATH }}
  - name: ELASTICSEARCH_CA_CERT_PATH
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_CA_CERT_PATH
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_INDEX_PATTERN }}
  - name: ELASTICSEARCH_INDEX_PATTERN
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_INDEX_PATTERN
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_DEFAULT_RESULT_SIZE }}
  - name: ELASTICSEARCH_DEFAULT_RESULT_SIZE
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_DEFAULT_RESULT_SIZE
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  {{- if .Values.connectorEnvVars.HASURA_CREDENTIALS_PROVIDER_URI }}
  - name: HASURA_CREDENTIALS_PROVIDER_URI
    value: {{ .Values.connectorEnvVars.HASURA_CREDENTIALS_PROVIDER_URI }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_CREDENTIALS_PROVIDER_KEY }}
  - name: ELASTICSEARCH_CREDENTIALS_PROVIDER_KEY
    valueFrom:
      secretKeyRef:
        key: ELASTICSEARCH_CREDENTIALS_PROVIDER_KEY
        name: {{ printf "%s-secret" (include "common.name" .) }}
  {{- end }}
  {{- include "validate.elasticsearch.credentialsProvider" . }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_CREDENTIALS_PROVIDER_MECHANISM }}
  - name: ELASTICSEARCH_CREDENTIALS_PROVIDER_MECHANISM
    value: {{ .Values.connectorEnvVars.ELASTICSEARCH_CREDENTIALS_PROVIDER_MECHANISM }}
  {{- end }}
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: {{ .Values.connectorEnvVars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  {{- if .Values.connectorEnvVars.OTEL_SERVICE_NAME }}
  - name: OTEL_SERVICE_NAME
    value: {{ .Values.connectorEnvVars.OTEL_SERVICE_NAME }}
  {{- else }}
  - name: OTEL_SERVICE_NAME
    value: {{ .Chart.Name }}
  {{- end }}
  {{- if .Values.connectorEnvVars.configDirectory }}
  - name: HASURA_CONFIGURATION_DIRECTORY
    value: {{ .Values.connectorEnvVars.configDirectory }}
  {{- end }}
