apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  DDN_CLI_PAT_TOKEN: {{ required "Error: .Values.ddnCliApiEnvVars.DDN_CLI_PAT_TOKEN is required!" .Values.ddnCliApiEnvVars.DDN_CLI_PAT_TOKEN | b64enc | quote }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ required "Error: .Values.ddnCliApiEnvVars.HASURA_GRAPHQL_ADMIN_SECRET is required!" .Values.ddnCliApiEnvVars.HASURA_GRAPHQL_ADMIN_SECRET | b64enc | quote }}
