apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  HASURA_SERVICE_TOKEN_SECRET: {{ .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  ELASTICSEARCH_URL: {{ .Values.connectorEnvVars.ELASTICSEARCH_URL | b64enc | quote }}
  ELASTICSEARCH_USERNAME: {{ .Values.connectorEnvVars.ELASTICSEARCH_USERNAME | b64enc | quote }}
  ELASTICSEARCH_PASSWORD: {{ .Values.connectorEnvVars.ELASTICSEARCH_PASSWORD | b64enc | quote }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_API_KEY }}
  ELASTICSEARCH_API_KEY: {{ .Values.connectorEnvVars.ELASTICSEARCH_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_CA_CERT_PATH }}
  ELASTICSEARCH_CA_CERT_PATH: {{ .Values.connectorEnvVars.ELASTICSEARCH_CA_CERT_PATH | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_INDEX_PATTERN }}
  ELASTICSEARCH_INDEX_PATTERN: {{ .Values.connectorEnvVars.ELASTICSEARCH_INDEX_PATTERN | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_DEFAULT_RESULT_SIZE }}
  ELASTICSEARCH_DEFAULT_RESULT_SIZE: {{ .Values.connectorEnvVars.ELASTICSEARCH_DEFAULT_RESULT_SIZE | b64enc | quote }}
  {{- end }}
{{- if .Values.observability.enabled }}
  otel-collector-config.yaml: {{ (tpl .Values.otel.config .) | b64enc | quote }}
{{- end }}

