apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  {{- if .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET }}
  HASURA_SERVICE_TOKEN_SECRET: {{ required "Error: .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET is required!" .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  {{- end }}
  ELASTICSEARCH_URL: {{ required "Error: .Values.connectorEnvVars.ELASTICSEARCH_URL is required!" .Values.connectorEnvVars.ELASTICSEARCH_URL | b64enc | quote }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_USERNAME }}
  ELASTICSEARCH_USERNAME: {{ required "Error: .Values.connectorEnvVars.ELASTICSEARCH_USERNAME is required!" .Values.connectorEnvVars.ELASTICSEARCH_USERNAME | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_PASSWORD }}
  ELASTICSEARCH_PASSWORD: {{ required "Error: .Values.connectorEnvVars.ELASTICSEARCH_PASSWORD is required!" .Values.connectorEnvVars.ELASTICSEARCH_PASSWORD | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_API_KEY }}
  ELASTICSEARCH_API_KEY: {{ .Values.connectorEnvVars.ELASTICSEARCH_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_CA_CERT_PATH }}
  ELASTICSEARCH_CA_CERT_PATH: {{ .Values.connectorEnvVars.ELASTICSEARCH_CA_CERT_PATH | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_INDEX_PATTERN }}
  ELASTICSEARCH_INDEX_PATTERN: {{ .Values.connectorEnvVars.ELASTICSEARCH_INDEX_PATTERN | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_DEFAULT_RESULT_SIZE }}
  ELASTICSEARCH_DEFAULT_RESULT_SIZE: {{ .Values.connectorEnvVars.ELASTICSEARCH_DEFAULT_RESULT_SIZE | b64enc | quote }}
  {{- end }}
  {{- if .Values.connectorEnvVars.ELASTICSEARCH_CREDENTIALS_PROVIDER_KEY }}
  ELASTICSEARCH_CREDENTIALS_PROVIDER_KEY: {{ .Values.connectorEnvVars.ELASTICSEARCH_CREDENTIALS_PROVIDER_KEY | b64enc | quote }}
  {{- end }}
