apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "minio.fullname" . }}-post-job
  labels:
    app: {{ include "minio.name" . }}-post-job
    chart: {{ include "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ include "minio.name" . }}-job
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: etc-path
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: minio-configuration
          projected:
            sources:
              - configMap:
                  name: {{ include "minio.fullname" . }}
              - secret:
                  name: {{ .Values.existingSecret.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: minio-make-bucket
          image: "{{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}"
          imagePullPolicy: {{ .Values.mcImage.pullPolicy }}
          command: ["/bin/sh", "/config/initialize"]
          env:
            - name: MINIO_ENDPOINT
              value: {{ include "minio.fullname" . }}
            - name: MINIO_PORT
              value: "9000"
          volumeMounts:
            - name: etc-path
              mountPath: /etc/minio/mc
            - name: tmp
              mountPath: /tmp
            - name: minio-configuration
              mountPath: /config
          {{- with .Values.jobResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.consoleUser }}
        - name: minio-make-user
          image: "{{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}"
          imagePullPolicy: {{ .Values.mcImage.pullPolicy }}
          command: ["/bin/sh", "/config/add-user"]
          env:
            - name: MINIO_ENDPOINT
              value: {{ include "minio.fullname" . }}
            - name: MINIO_PORT
              value: "9000"
          volumeMounts:
            - name: etc-path
              mountPath: /etc/minio/mc
            - name: tmp
              mountPath: /tmp
            - name: minio-configuration
              mountPath: /config
          {{- with .Values.jobResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
