apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  {{- if and .Values.persistence.storageClass (ne .Values.persistence.storageClass "-") }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- else if eq (default "" .Values.persistence.storageClass) "-" }}
  storageClassName: ""
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
