apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  HASURA_SERVICE_TOKEN_SECRET: {{ required "Error: .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET is required!" .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  HASURA_BIGQUERY_SERVICE_KEY: {{ required "Error: .Values.connectorEnvVars.HASURA_BIGQUERY_SERVICE_KEY is required!" .Values.connectorEnvVars.HASURA_BIGQUERY_SERVICE_KEY | b64enc | quote }}
  HASURA_BIGQUERY_PROJECT_ID: {{ required "Error: .Values.connectorEnvVars.HASURA_BIGQUERY_PROJECT_ID is required!" .Values.connectorEnvVars.HASURA_BIGQUERY_PROJECT_ID | b64enc | quote }}
  HASURA_BIGQUERY_DATASET_ID: {{ required "Error: .Values.connectorEnvVars.HASURA_BIGQUERY_DATASET_ID is required!" .Values.connectorEnvVars.HASURA_BIGQUERY_DATASET_ID | b64enc | quote }}
  {{- if .Values.observability.enabled }}
  otel-collector-config.yaml: {{ (tpl .Values.otel.config .) | b64enc | quote }}
  {{- end }}