apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  HASURA_SERVICE_TOKEN_SECRET: {{ .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  CONNECTION_URI: {{ .Values.connectorEnvVars.CONNECTION_URI | b64enc | quote }}
  CLIENT_CERT: {{ .Values.connectorEnvVars.CLIENT_CERT | b64enc | quote }}
  CLIENT_KEY: {{ .Values.connectorEnvVars.CLIENT_KEY | b64enc | quote }}
  ROOT_CERT: {{ .Values.connectorEnvVars.ROOT_CERT | b64enc | quote }}
{{- if .Values.otel.deployOtelCollector }}
  otel-collector-config.yaml: {{ (tpl .Values.otel.config .) | b64enc | quote }}
{{- end }}
   
