apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  HASURA_SERVICE_TOKEN_SECRET: {{ required "Error: .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET is required!" .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  {{- if .Values.connectorEnvVars.NDC_OAS_DOCUMENT_URI }}
  NDC_OAS_DOCUMENT_URI: {{ .Values.connectorEnvVars.NDC_OAS_DOCUMENT_URI | b64enc | quote }}
  {{- end }}
  NDC_OAS_BASE_URL: {{ required "Error: .Values.connectorEnvVars.NDC_OAS_BASE_URL is required!" .Values.connectorEnvVars.NDC_OAS_BASE_URL | b64enc | quote }}
  NDC_OAS_LAMBDA_PRETTY_LOGS: {{ required "Error: .Values.connectorEnvVars.NDC_OAS_LAMBDA_PRETTY_LOGS is required!" .Values.connectorEnvVars.NDC_OAS_LAMBDA_PRETTY_LOGS | toString | b64enc }}
  NDC_OAS_FILE_OVERWRITE: {{ required "Error: .Values.connectorEnvVars.NDC_OAS_FILE_OVERWRITE is required!" .Values.connectorEnvVars.NDC_OAS_FILE_OVERWRITE | toString | b64enc }}
  {{- if .Values.observability.enabled }}
  otel-collector-config.yaml: {{ (tpl .Values.otel.config .) | b64enc | quote }}
  {{- end }}