apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
  labels:
    app: {{template "common.name" .}}
data:
  {{- if .Values.initContainers.gitSync.enabled }}
  run.sh: |
    #!/usr/bin/env bash
    set -eu -o pipefail
    {{- if .Values.initContainers.gitSync.depsPackaged }}
    export NODE_PATH="${HASURA_CONFIGURATION_DIRECTORY}/node_modules"
    {{- else }}
    export NODE_PATH=/functions/node_modules
    {{- end }}

    # Currently we are unable to write to /functions directory and requires
    # a change to the Dockerfile
    # Hence copy node_modules and the connector app contents for work-dir(git-sync)
    # to a place where we have access and run from there
    mkdir -p /tmp/app && cd /tmp/app
    cp -r "${HASURA_CONFIGURATION_DIRECTORY}/." /tmp/app/

    {{- if not .Values.initContainers.gitSync.depsPackaged }}
    cp -r /functions/node_modules /tmp/app/
    {{- end }}

    # Read the npm start script from package.json then exec it to ensure that
    # it is the root process in the container, so that signals (ie SIGTERM)
    # are propagated properly. "npm start" does not propagate SIGTERM to the
    # actual started process
    START_CMD=$(jq -r ".scripts.start" "package.json")
    PATH=$PATH:/tmp/app/node_modules/.bin exec $START_CMD
  {{- else }}
  run.sh: |
    #!/usr/bin/env bash
    echo "git-sync is not enabled. So falling back to use default start script."
    /scripts/start.sh
  {{- end }}