apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  HASURA_SERVICE_TOKEN_SECRET: {{ required "Error: .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET is required!" .Values.connectorEnvVars.HASURA_SERVICE_TOKEN_SECRET | b64enc | quote }}
  GRAPHQL_ENDPOINT: {{ required "Error: .Values.connectorEnvVars.GRAPHQL_ENDPOINT is required!" .Values.connectorEnvVars.GRAPHQL_ENDPOINT | b64enc | quote }}
{{- if .Values.observability.enabled }}
  otel-collector-config.yaml: {{ (tpl .Values.otel.config .) | b64enc | quote }}
{{- end }}

